const projectList = {
  projects: [
    {
      id: 'celia',
      title: 'Célia Lopez',
      description: 'Célia Lopez is a junior 3D and interactive designer. I helped her to realize her portfolio.',
      date: '2018',
      link: 'View website',
      url: 'http://www.celialopez.fr',
      role: '<div>Creative Developer</div>',
      technologies: '<div>WebGL</div><div>ThreeJS</div>',
      clients: 'Célia Lopez',
      awards: '<div><a href="https://www.awwwards.com/sites/celia-lopez" target="_blank">Awwwards - SOTD</a></div><div><a href="https://thefwa.com/cases/portfolio-of-celia-lopez" target="_blank">FWA - SOTD</a></div><div><a href="https://www.cssdesignawards.com/sites/celia-lopez-portfolio/32742/" target="_blank">CSSDesignAwards - SOTD</a></div>',
      medias: [
        { type: 'image', url: 'images/projects/celia/1.jpg' },
        { type: 'image', url: 'images/projects/celia/2.jpg' },
        { type: 'video', url: 'videos/projects/celia/1.mp4' },
        { type: 'video', url: 'videos/projects/celia/2.mp4' },
      ],
    },
    {
      id: 'resn-little-helper',
      title: 'Resn\'s Little Helper',
      description: 'A long time ago, before St. Nick, Father Christmas, Kris Kringle, Santa or whatever you wanna call him, there was an elf, some ’shrooms and a flute. The real first Christmas. Truth. We realized this special christmas card at Resn.',
      date: '<a href="http://resn.co.nz/" target="_blank">Resn</a> 2017',
      link: 'View website',
      url: 'http://littlehelper.resn.global/',
      role: '<div>Creative Developer</div>',
      technologies: '<div>WebGL</div><div>ThreeJS</div>',
      clients: null,
      awards: '<div><a href="https://www.awwwards.com/sites/resns-little-helper" target="_blank">Awwwards - SOTD</a></div><div><a href="https://thefwa.com/cases/resns-little-helper" target="_blank">FWA - SOTM</a></div>',
      medias: [
        { type: 'image', url: 'images/projects/resn-little-helper/1.jpg' },
        { type: 'image', url: 'images/projects/resn-little-helper/2.jpg' },
        { type: 'image', url: 'images/projects/resn-little-helper/3.jpg' },
        { type: 'video', url: 'videos/projects/resn-little-helper/1.mp4' },
      ],
    },
    {
      id: 'hp',
      title: 'HP Sound in Color',
      description: 'Capture any piece of audio on your Android handheld or desktop and transform it into a lush, abstract piece of art. We realized this website to promote the HP Spectre x360 computer. I mainly worked on the UI and it\'s animations.',
      date: '<a href="http://resn.co.nz/" target="_blank">Resn</a> 2016',
      link: 'View website',
      url: 'https://www.hpsoundincolor.com/',
      role: '<div>Creative Developer</div>',
      technologies: '<div>WebGL</div><div>ThreeJS</div>',
      clients: '<div>HP</div>',
      awards: '<div><a href="https://www.awwwards.com/sites/hp-sound-in-color" target="_blank">Awwwards - SOTD</a></div><div><a href="https://thefwa.com/cases/hp-sound-in-color" target="_blank">FWA - SOTD</a></div><div><a href="https://www.cssdesignawards.com/sites/hp-sound-in-color/29728/" target="_blank">CSSDesignAwards - SOTD</a></div>',
      medias: [
        { type: 'image', url: 'images/projects/hp/1.jpg' },
        { type: 'image', url: 'images/projects/hp/2.jpg' },
        { type: 'image', url: 'images/projects/hp/3.jpg' },
        { type: 'image', url: 'images/projects/hp/4.jpg' },
        { type: 'video', url: 'videos/projects/hp/1.mp4' },
      ],
    },
    {
      id: 'tsuki8',
      title: 'Tsuki 8',
      description: 'Tsuki8 is an artistic project realized by the french media-artists <a href="http://makioandfloz.com/" target="_blank">Makio&Floz</a>. I joined them for one month to help them right after I ended Gobelins school. We traveled around Japan, discovered the country, met people and got inspired by it to do projection mapping, which means using a projector to project animations and visuals on nature & buildings.',
      date: '<a href="http://makioandfloz.com/" target="_blank">Makio&Floz</a> 2016',
      link: 'View website',
      url: 'http://tsuki8.makioandfloz.com/',
      role: '<div>Developer</div><div>Pre-production assistant</div>',
      technologies: '<div>WebGL</div><div>ThreeJS</div>',
      clients: null,
      awards: null,
      medias: [
        { type: 'image', url: 'images/projects/tsuki8/1.jpg' },
        { type: 'image', url: 'images/projects/tsuki8/2.jpg' },
        { type: 'video', url: 'videos/projects/tsuki8/1.mp4' },
        { type: 'video', url: 'videos/projects/tsuki8/2.mp4' },
      ],
    },
    {
      id: 'speedfactory',
      title: 'Adidas Speedfactory',
      description: 'A globally touring activation showcasing adidas’ high-tech, data driven footwear and it’s manufacturing process. Visitors experience a series of interactive installations that teach the adidas Speedfactory key approaches of Innovation, Co-Creation and Speed. Below are some medias coming from the website we made at Resn.',
      date: '<a href="http://resn.co.nz/" target="_blank">Resn</a> 2017 / 2018',
      link: 'View website',
      url: 'https://www.adidas.co.uk/speedfactory',
      role: '<div>Creative Developer</div>',
      technologies: '<div>WebGL</div><div>ThreeJS</div>',
      clients: '<div>Adidas</div>',
      awards: '<div><a href="https://www.awwwards.com/sites/adidas-speedfactory" target="_blank">Awwwards - SOTD</a></div><div><a href="https://thefwa.com/cases/adidas-speedfactory" target="_blank">FWA - SOTD</a></div><div><a href="https://www.cssdesignawards.com/sites/adidas-speedfactory/32036/" target="_blank">CSSDesignAwards - SOTM</a></div>',
      medias: [
        { type: 'image', url: 'images/projects/speedfactory/1.jpg' },
        { type: 'image', url: 'images/projects/speedfactory/2.jpg' },
        { type: 'image', url: 'images/projects/speedfactory/3.jpg' },
        { type: 'video', url: 'videos/projects/speedfactory/1.mp4' },

      ],
    },
    {
      id: 'nmd',
      title: 'Adidas NMD',
      description: 'Adidas Original NMD 2017 combined the launch of a new apparel category alongside a fresh update of shoe coulourways for the year. Tailored towards the streetwear audience who live and breathe the urban nightlife. We made the website at Resn. I mainly worked on the WebGL background and some UI animations.',
      date: '<a href="http://resn.co.nz/" target="_blank">Resn</a> 2017',
      link: 'Website offline',
      role: '<div>Creative Developer</div>',
      technologies: '<div>WebGL</div><div>ThreeJS</div>',
      clients: '<div>Adidas</div>',
      awards: '<div><a href="https://www.awwwards.com/sites/adidas-originals-nmd" target="_blank">Awwwards - SOTD</a></div><div><a href="https://thefwa.com/cases/adidas-originals-nmd" target="_blank">FWA - SOTD</a></div><div><a href="https://www.cssdesignawards.com/sites/adidas-nmd/30520/" target="_blank">CSSDesignAwards - SOTD</a></div>',
      medias: [
        { type: 'image', url: 'images/projects/nmd/1.jpg' },
        { type: 'image', url: 'images/projects/nmd/2.jpg' },
        { type: 'image', url: 'images/projects/nmd/3.jpg' },
        { type: 'video', url: 'videos/projects/nmd/1.mp4' },
      ],
    },
    {
      id: 'lusine',
      title: 'Delicious Moment',
      description: 'This experience for bread maker L\'usine is aimed at kids and parents to promote food creativity and enjoyment at home. The site allows users to first create a sandwich using our large variety of fillings, toppings, breads and condiments. Then you can download the receipe and also have a look to the others created sandwichs beforehand. We made this website at Resn. I mainly worked on all the animations and some WebGL parts.',
      date: '<a href="http://resn.co.nz/" target="_blank">Resn</a> 2016',
      link: 'Website offline',
      role: '<div>Creative Developer</div>',
      technologies: '<div>WebGL</div><div>ThreeJS</div>',
      clients: '<div>Adidas</div>',
      awards: '<div><a href="https://www.awwwards.com/sites/adidas-originals-nmd" target="_blank">Awwwards - SOTD</a></div><div><a href="https://thefwa.com/cases/adidas-originals-nmd" target="_blank">FWA - SOTD</a></div><div><a href="https://www.cssdesignawards.com/sites/adidas-nmd/30520/" target="_blank">CSSDesignAwards - SOTD</a></div>',
      medias: [
        { type: 'image', url: 'images/projects/lusine/1.jpg' },
        { type: 'image', url: 'images/projects/lusine/2.jpg' },
        { type: 'image', url: 'images/projects/lusine/3.jpg' },
        { type: 'image', url: 'images/projects/lusine/4.jpg' },
        { type: 'image', url: 'images/projects/lusine/5.jpg' },
        { type: 'image', url: 'images/projects/lusine/6.jpg' },
        { type: 'video', url: 'videos/projects/lusine/1.mp4' },
      ],
    },
  ],

  getProject(id) {
    return projectList.projects.find( project => project.id === id );
  },

};

module.exports = projectList;
